### ISSUE TITLE
Installing recode on termux in android

### ISSUE THREAD

**Issue by pleiozc** [rrthomas/recode#30]
Hi rrthomas

Could you take a look at this issue with building recode on termux (details [here](https://github.com/Bugswriter/tuxi/issues/154)). I'm trying to install tuxi. It looks like it cannot be installed unless it gets root permission. Any way to work around it?

**Comment by rrthomas** [comment]
There's nothing specific to recode here. Just like any normal `configure` script, set a suitable `--prefix`, in this case, one that does not need root permissions.

First, you should really be using this repo, not Pinard's (unfortunately I only took over the project some years after he died without appointing a successor).

Secondly, I just tried building the current git master on termux; I had one problem, because I could not install `Locale::gettext`, which help2man needs, but after hacking around that (to build the man page), I was able to run `make install` with no problem.

**Comment by rrthomas** [comment]
(I do not know whether it is impossible to install `Locale::gettext` on Termux, in which case I would welcome a patch to `recode` to cope with this case, or whether there is some trick to install the package.)
